apiVersion: v1
kind: Service
metadata:
  name: ad-svc
spec:
  type: ClusterIP
  ports:
    - port: 389
      targetPort: 389

#####################
# use ldap://ad-svc #
#####################

---
apiVersion: v1
kind: Endpoints
metadata:
  name: ad-svc
subsets:
  - addresses:
      - ip: 10.1.0.10
    ports:
      - port: 389
