apiVersion: v1
kind: Service
metadata:
  name: ad-svc
spec:
  ports:
    - name: active-directory
      protocol: TCP
      port: 389
      targetPort: 389
      nodePort: 0

---
apiVersion: v1
kind: Endpoints
metadata:
  name: ad-svc
subsets:
  - addresses:
      - ip: 10.1.0.10
    ports:
      - name: active-directory
        port: 389
