apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  # type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017

##################################
# use mongodb://mongo-svc/dbname #
##################################

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo-svc
subsets:
  - addresses:
      - ip: 10.1.2.6
    ports:
      - port: 27017
