apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  ports:
    - port: 27017

##############################
# use mongodb://mongo/dbname #
##############################

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo
subsets:
  - addresses:
      - ip: 10.1.2.6
    ports:
      - name: mongo
        port: 27017
