apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo5
  labels:
    app: mongo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo5
  template:
    metadata:
      labels:
        app: mongo5
    spec:
      containers:
        - name: mongo5
          image: mongo:5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo5-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo5-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo5
  labels:
    service: mongo5
spec:
  type: LoadBalancer
  selector:
    app: mongo5
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo5-secret
  labels:
    app: mongo5
type: Opaque
data:
  username: YjJi # echo -n 'b2b' | base64
  password: VHFNekFSU0tCOU53a1FRSnMzVm0= # echo -n 'TqMzARSKB9NwkQQJs3Vm' | base64
