apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  # type: ClusterIP
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 0
###################################
# use mongodb://mongo-svc/dbname #
#################################

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo-svc
subsets:
  - addresses:
      - ip: 10.1.2.6
    ports:
      - name: mongodb
        port: 27017
