apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo3
  labels:
    app: mongo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo3
  template:
    metadata:
      labels:
        app: mongo3
    spec:
      containers:
        - name: mongo3
          image: mongo:3
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo3-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo3-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo3
  labels:
    service: mongo3
spec:
  type: LoadBalancer
  selector:
    app: mongo3
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo3-secret
  labels:
    app: mongo3
type: Opaque
data:
  username: YjJi # echo -n 'b2b' | base64
  password: VHFNekFSU0tCOU53a1FRSnMzVm0= # echo -n 'TqMzARSKB9NwkQQJs3Vm' | base64
